site_name: Statistical Mechanics and Thermodynamics
repo_url: https://hephaestus-energy-forge.github.io/Hephaestus-Energy-Forge/

nav:
  - About: 'index.md'
  - Statistical mechanics:
      - Basics of probability theory: '1_basics_of_probability_theory.md'

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_page_read_source: "execute:on_page_read_source"
        on_page_markdown: "execute:on_page_markdown"

theme:
  name: material
  logo: logo.png
  features:
    - navigation.instant
    - content.code.copy
  palette:
    primary: 'white'
    accent: 'indigo'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.extra
  - abbr
  - footnotes
  - meta

extra_css:
  - 'https://use.fontawesome.com/releases/v5.8.1/css/all.css'
  - 'styles/mathjax_hotfix.css'
  - 'styles/thebelab.css'

extra_javascript:
  - 'scripts/mathjaxhelper.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
  - 'https://cdn.plot.ly/plotly-latest.min.js'

copyright: "Copyright © 2024 Konstantin Unruh"